### ISSUE TITLE
Functional interface parsing has ERROR

### ISSUE THREAD

**Issue by TTitcombe** [fwcd/tree-sitter-kotlin#87]
There is an error parsing functional interfaces.

For example (from kotlinlang.org):

```kotlin
fun interface IntPredicate {
   fun accept(i: Int): Boolean
}
```

The node which should represent the body/`accept` method is an error, rather than correctly parsing out the abstract function.

**Comment by bricka** [comment]
@VladimirMakaev Could you reopen this issue, since we had to rollback the change?

And copying my comment from the MR:

Did it break because of the generated parser? If so, how can we push this forward? Could someone who can generate the parser correctly check out this branch, generate the parser, and then push that?

**Comment by amaanq** [comment]
I believe this is fixed and parses correctly @ https://github.com/tree-sitter-grammars/tree-sitter-kotlin
